/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4_kalkulator;
import java.util.*;
import java.util.concurrent.Phaser;

/**
 *
 * @author USER
 */
public class Tampilan_Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan_Kalkulator
     */
     int newblank = 0;
     String anggka = "";
     int Fungsi = 0;
     Double x;
     Double y;
    public Tampilan_Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Kurang = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        Perkalian = new javax.swing.JButton();
        Samadengan = new javax.swing.JButton();
        Pembagian = new javax.swing.JButton();
        Pecahan = new javax.swing.JButton();
        Pangkat = new javax.swing.JButton();
        Akar = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        ClearEntry = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Enam = new javax.swing.JButton();
        Lima = new javax.swing.JButton();
        Empat = new javax.swing.JButton();
        Delapan = new javax.swing.JButton();
        Sembilan = new javax.swing.JButton();
        Tujuh = new javax.swing.JButton();
        Nol = new javax.swing.JButton();
        InputValue = new javax.swing.JTextField();
        Satu = new javax.swing.JButton();
        Dua = new javax.swing.JButton();
        Tiga = new javax.swing.JButton();
        Koma = new javax.swing.JButton();
        PlusMinus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));

        Panel.setBackground(new java.awt.Color(153, 153, 153));

        Kurang.setBackground(new java.awt.Color(51, 51, 51));
        Kurang.setForeground(new java.awt.Color(255, 255, 255));
        Kurang.setText("-");
        Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KurangActionPerformed(evt);
            }
        });

        Tambah.setBackground(new java.awt.Color(51, 51, 51));
        Tambah.setForeground(new java.awt.Color(255, 255, 255));
        Tambah.setText("+");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Perkalian.setBackground(new java.awt.Color(51, 51, 51));
        Perkalian.setForeground(new java.awt.Color(255, 255, 255));
        Perkalian.setText("x");
        Perkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerkalianActionPerformed(evt);
            }
        });

        Samadengan.setBackground(new java.awt.Color(51, 51, 51));
        Samadengan.setForeground(new java.awt.Color(255, 255, 255));
        Samadengan.setText("=");
        Samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamadenganActionPerformed(evt);
            }
        });

        Pembagian.setBackground(new java.awt.Color(51, 51, 51));
        Pembagian.setForeground(new java.awt.Color(255, 255, 255));
        Pembagian.setText("÷");
        Pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembagianActionPerformed(evt);
            }
        });

        Pecahan.setBackground(new java.awt.Color(51, 51, 51));
        Pecahan.setForeground(new java.awt.Color(255, 255, 255));
        Pecahan.setText("1/x");
        Pecahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PecahanActionPerformed(evt);
            }
        });

        Pangkat.setBackground(new java.awt.Color(51, 51, 51));
        Pangkat.setForeground(new java.awt.Color(255, 255, 255));
        Pangkat.setText("^");
        Pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PangkatActionPerformed(evt);
            }
        });

        Akar.setBackground(new java.awt.Color(51, 51, 51));
        Akar.setForeground(new java.awt.Color(255, 255, 255));
        Akar.setText("√");
        Akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkarActionPerformed(evt);
            }
        });

        Delete.setText("Del");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        ClearEntry.setBackground(new java.awt.Color(255, 102, 0));
        ClearEntry.setText("CE");
        ClearEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearEntryActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(255, 102, 0));
        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Enam.setText("6");
        Enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnamActionPerformed(evt);
            }
        });

        Lima.setText("5");
        Lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimaActionPerformed(evt);
            }
        });

        Empat.setText("4");
        Empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpatActionPerformed(evt);
            }
        });

        Delapan.setText("8");
        Delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelapanActionPerformed(evt);
            }
        });

        Sembilan.setText("9");
        Sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SembilanActionPerformed(evt);
            }
        });

        Tujuh.setText("7");
        Tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuhActionPerformed(evt);
            }
        });

        Nol.setText("0");
        Nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NolActionPerformed(evt);
            }
        });

        InputValue.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        InputValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InputValue.setText("0"); // NOI18N
        InputValue.setToolTipText("");
        InputValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputValueActionPerformed(evt);
            }
        });

        Satu.setText("1");
        Satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuActionPerformed(evt);
            }
        });

        Dua.setText("2");
        Dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuaActionPerformed(evt);
            }
        });

        Tiga.setText("3");
        Tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TigaActionPerformed(evt);
            }
        });

        Koma.setBackground(new java.awt.Color(255, 102, 0));
        Koma.setText(".");
        Koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KomaActionPerformed(evt);
            }
        });

        PlusMinus.setBackground(new java.awt.Color(255, 102, 0));
        PlusMinus.setText("+/-");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputValue, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(ClearEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Satu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Empat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Dua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lima, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Delapan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Nol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Enam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Koma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Perkalian, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Samadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addComponent(Pecahan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Akar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Pembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputValue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ClearEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pecahan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Akar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Pembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Satu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Empat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lima, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Enam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delapan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Koma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(Perkalian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Samadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomaActionPerformed
        // TODO add your handling code here:
        if (anggka.contains(".")==false) {
            anggka += ".";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_KomaActionPerformed

    private void TigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TigaActionPerformed
        // TODO add your handling code here:
        if (anggka == "0") {
            anggka = "3";
            InputValue.setText(anggka);
            newblank=0;
        }
        else if (newblank == 1) {
            anggka = "3";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "3";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_TigaActionPerformed

    private void DuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuaActionPerformed
        // TODO add your handling code here:
        if (anggka == "0") {
            anggka = "2";
            InputValue.setText(anggka);
            newblank=0;
        }
        else if (newblank == 1) {
            anggka = "2";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "2";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_DuaActionPerformed

    private void SatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuActionPerformed
        // TODO add your handling code here:
       if (anggka == "0") {
            anggka = "1";
            InputValue.setText(anggka);
            newblank=0;
        }
       else if (newblank == 1) {
            anggka = "1";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "1";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_SatuActionPerformed

    private void InputValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputValueActionPerformed

    private void NolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NolActionPerformed
        // TODO add your handling code here:
        if (anggka == "0") {
            anggka = "0";
            InputValue.setText(anggka);
            newblank=0;
        }
        else if (newblank == 1) {
            anggka = "0";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "0";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_NolActionPerformed

    private void TujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuhActionPerformed
        // TODO add your handling code here:
       if (anggka == "0") {
            anggka = "7";
            InputValue.setText(anggka);
            newblank=0;
        }
        else if (newblank == 1) {
            anggka = "7";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "7";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_TujuhActionPerformed

    private void SembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SembilanActionPerformed
        // TODO add your handling code here:
        if (anggka == "0") {
            anggka = "9";
            InputValue.setText(anggka);
            newblank=0;
        }
        else if (newblank == 1) {
            anggka = "9";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "9";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_SembilanActionPerformed

    private void DelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelapanActionPerformed
        // TODO add your handling code here:
        if (anggka == "0") {
            anggka = "8";
            InputValue.setText(anggka);
            newblank=0;
        }
        else if (newblank == 1) {
            anggka = "8";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "8";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_DelapanActionPerformed

    private void EmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpatActionPerformed
        // TODO add your handling code here:
        if (anggka == "0") {
            anggka = "4";
            InputValue.setText(anggka);
            newblank=0;
        }
        else if (newblank == 1) {
            anggka = "4";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "4";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_EmpatActionPerformed

    private void LimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimaActionPerformed
        // TODO add your handling code here:
        if (anggka == "0") {
            anggka = "5";
            InputValue.setText(anggka);
            newblank=0;
        }
        else if (newblank == 1) {
            anggka = "5";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "5";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_LimaActionPerformed

    private void EnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnamActionPerformed
        // TODO add your handling code here:
        if (anggka == "0") {
            anggka = "6";
            InputValue.setText(anggka);
            newblank=0;
        }
        else if (newblank == 1) {
            anggka = "6";
            InputValue.setText(anggka);
            newblank=0;
        }
        else{
            anggka += "6";
            InputValue.setText(anggka);
        }
    }//GEN-LAST:event_EnamActionPerformed

    private void AkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkarActionPerformed
        // TODO add your handling code here:
        if (Fungsi == 0) {
            x = Double.parseDouble(anggka);
            anggka = "0";
            InputValue.setText("0");
            Fungsi=6;
            newblank = 1;
        } else {
            newblank = 1;
             y = Double.parseDouble(anggka);
            switch (Fungsi)
            {
                case 1:
                x = x + y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=6;
                break;
                case 2:
                x = x - y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=6;
                break;
                case 3:
                x = x * y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=6;
                break;
                case 4:
                x = x / y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=6;
                break;
                case 5:
                double xawal1 = x;
                for (int i = 1; i < y; i++) {
                    x = x*xawal1;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=6;
                break;
                case 6:
                double xawal2 = x;
                for (int i = 1; i < y; i++) {
                    x = x / xawal2;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=6;
                break;
                default:
                break;
            }
        }
    }//GEN-LAST:event_AkarActionPerformed

    private void PangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PangkatActionPerformed
        // TODO add your handling code here:
        if (Fungsi == 0) {
            x = Double.parseDouble(anggka);
            anggka = "0";
            InputValue.setText("0");
            Fungsi=5;
            newblank = 1;
        } else {
            newblank = 1;
            y = Double.parseDouble(anggka);
            switch (Fungsi)
            {
                case 1:
                x = x + y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=5;
                break;
                case 2:
                x = x - y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=5;
                break;
                case 3:
                x = x * y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=5;
                break;
                case 4:
                x = x / y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=5;
                break;
                case 5:
                double xawal1 = x;
                for (int i = 1; i < y; i++) {
                    x = x*xawal1;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=5;
                break;
                case 6:
                double xawal2 = x;
                for (int i = 1; i < y; i++) {
                    x = x / xawal2;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=5;
                break;
                default:
                break;
            }
        }
    }//GEN-LAST:event_PangkatActionPerformed

    private void PecahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PecahanActionPerformed
        // TODO add your handling code here:
        x = Double.parseDouble(anggka);
        x = 1 / x;
        anggka = Double.toString(x);
        InputValue.setText(anggka);
        newblank = 1;
    }//GEN-LAST:event_PecahanActionPerformed

    private void PembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembagianActionPerformed
        // TODO add your handling code here:
        if (Fungsi == 0) {
            x = Double.parseDouble(anggka);
            anggka = "0";
            InputValue.setText("0");
            Fungsi=4;
            newblank = 1;
        } else {
            newblank = 1;
            y = Double.parseDouble(anggka);
            switch (Fungsi)
            {
                case 1:
                x = x + y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=4;
                break;
                case 2:
                x = x - y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=4;
                break;
                case 3:
                x = x * y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=4;
                break;
                case 4:
                x = x / y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=4;
                break;
                case 5:
                double xawal1 = x;
                for (int i = 1; i < y; i++) {
                    x = x*xawal1;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=4;
                break;
                case 6:
                double xawal2 = x;
                for (int i = 1; i < y; i++) {
                    x = x / xawal2;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=4;
                break;
                default:
                break;
            }
        }
    }//GEN-LAST:event_PembagianActionPerformed

    private void SamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamadenganActionPerformed
        // TODO add your handling code here:
        y = Double.parseDouble(anggka);
        newblank = 1;
        switch (Fungsi)
        {
            case 1:
            x = x + y;
            y = 0.0;
            anggka = Double.toString(x);
            InputValue.setText(anggka);
            Fungsi=0;
            break;
            case 2:
            x = x - y;
            y = 0.0;
            anggka = Double.toString(x);
            InputValue.setText(anggka);
            Fungsi=0;
            break;
            case 3:
            x = x * y;
            y = 0.0;
            anggka = Double.toString(x);
            InputValue.setText(anggka);
            Fungsi=0;
            break;
            case 4:
            x = x / y;
            y = 0.0;
            anggka = Double.toString(x);
            InputValue.setText(anggka);
            Fungsi=0;
            break;
            case 5:
            double xawal1 = x;
            for (int i = 1; i < y; i++) {
                x = x*xawal1;
            }
            y = 0.0;
            anggka = Double.toString(x);
            InputValue.setText(anggka);
            Fungsi=0;
            break;
            case 6:
            double xawal2 = x;
            for (int i = 1; i < y; i++) {
                x = x / xawal2;
            }
            y = 0.0;
            anggka = Double.toString(x);
            InputValue.setText(anggka);
            Fungsi=0;
            break;
            default:
            break;
        }
    }//GEN-LAST:event_SamadenganActionPerformed

    private void PerkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerkalianActionPerformed
        // TODO add your handling code here:
        if (Fungsi == 0) {
            newblank = 1;
            x = Double.parseDouble(anggka);
            anggka = "0";
            InputValue.setText("0");
            Fungsi=3;
        } else {
            newblank = 1;
            y = Double.parseDouble(anggka);
            switch (Fungsi)
            {
                case 1:
                x = x + y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=3;
                break;
                case 2:
                x = x - y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=3;
                break;
                case 3:
                x = x * y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=3;
                break;
                case 4:
                x = x / y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=3;
                break;
                case 5:
                double xawal1 = x;
                for (int i = 1; i < y; i++) {
                    x = x*xawal1;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=3;
                break;
                case 6:
                double xawal2 = x;
                for (int i = 1; i < y; i++) {
                    x = x / xawal2;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=3;
                break;
                default:
                break;
            }
        }
    }//GEN-LAST:event_PerkalianActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        if (Fungsi == 0) {
            newblank = 1;
            x = Double.parseDouble(anggka);
            anggka = "0";
            InputValue.setText("0");
            Fungsi=1;
        } else {
            newblank = 1;
            y = Double.parseDouble(anggka);
            switch (Fungsi)
            {
                case 1:
                x = x + y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=1;
                break;
                case 2:
                x = x - y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=1;
                break;
                case 3:
                x = x * y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=1;
                break;
                case 4:
                x = x / y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=1;
                break;
                case 5:
                double xawal1 = x;
                for (int i = 1; i < y; i++) {
                    x = x*xawal1;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=1;
                break;
                case 6:
                double xawal2 = x;
                for (int i = 1; i < y; i++) {
                    x = x / xawal2;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=1;
                break;
                default:
                break;
            }
        }
    }//GEN-LAST:event_TambahActionPerformed

    private void KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangActionPerformed
        // TODO add your handling code here:
        if (Fungsi == 0) {
            newblank = 1;
            x = Double.parseDouble(anggka);
            anggka = "0";
            InputValue.setText("0");
            Fungsi=2;
        } else {
            newblank = 1;
            y = Double.parseDouble(anggka);
            switch (Fungsi)
            {
                case 1:
                x = x + y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=2;
                break;
                case 2:
                x = x - y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=2;
                break;
                case 3:
                x = x * y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=2;
                break;
                case 4:
                x = x / y;
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=2;
                break;
                case 5:
                double xawal1 = x;
                for (int i = 1; i < y; i++) {
                    x = x*xawal1;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=2;
                break;
                case 6:
                double xawal2 = x;
                for (int i = 1; i < y; i++) {
                    x = x / xawal2;
                }
                y = 0.0;
                anggka = Double.toString(x);
                InputValue.setText(anggka);
                Fungsi=2;
                break;
                default:
                break;
            }
        }
    }//GEN-LAST:event_KurangActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        Fungsi=0;
        InputValue.setText("0");
        anggka="0";
        x=0.0;
    }//GEN-LAST:event_ClearActionPerformed

    private void ClearEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearEntryActionPerformed
        // TODO add your handling code here:
        InputValue.setText("0");
        anggka="0";
    }//GEN-LAST:event_ClearEntryActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        anggka=anggka.substring(0,anggka.length() - 1);
        InputValue.setText(anggka);
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan_Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan_Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Akar;
    private javax.swing.JButton Clear;
    private javax.swing.JButton ClearEntry;
    private javax.swing.JButton Delapan;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Dua;
    private javax.swing.JButton Empat;
    private javax.swing.JButton Enam;
    private javax.swing.JTextField InputValue;
    private javax.swing.JButton Koma;
    private javax.swing.JButton Kurang;
    private javax.swing.JButton Lima;
    private javax.swing.JButton Nol;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton Pangkat;
    private javax.swing.JButton Pecahan;
    private javax.swing.JButton Pembagian;
    private javax.swing.JButton Perkalian;
    private javax.swing.JButton PlusMinus;
    private javax.swing.JButton Samadengan;
    private javax.swing.JButton Satu;
    private javax.swing.JButton Sembilan;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Tiga;
    private javax.swing.JButton Tujuh;
    // End of variables declaration//GEN-END:variables
}
